Support sync by install
cnpm/cnpmcore pull request #337
Opened 2022-10-20 09:24 UTC by laoboxie

1、修复 syncMode=exist 同步包定时任务不执行的问题
2、支持包不存在时自动同步和重定向到 sourceRegistry 的功能 close #335 

参考：
1、https://github.com/cnpm/cnpmcore/pull/50/files#diff-97cbafa75ed0bae6a1f0a2df0676c00f56b9cf8944b04ddb82d6dd0ab141961f
2、https://github.com/cnpm/cnpmjs.org/blob/master/middleware/sync_by_install.js

2022-10-20 10:10 UTC, fengmk2 commented on app/port/controller/package/ShowPackageController.ts
> +      throw this.createPackageNotFoundError(fullname, undefined, allowSync);
这个逻辑是否就做到 createPackageNotFoundError 方法内部就好了？

2022-10-20 10:13 UTC, fengmk2 commented
加一下单元测试。

2022-10-21 03:16 UTC, laoboxie commented on app/port/controller/package/ShowPackageController.ts
> +      throw this.createPackageNotFoundError(fullname, undefined, allowSync);
做到 createPackageNotFoundError 方法内部应该不合适，根据 cnpm.org 的代码，syncByInstall  中间件只会加在两个接口上（showPackage 和 showPackageVersion），但是 createPackageNotFoundError 还被其他很多地方使用到（例如 packageBlock/packageTag/...）

2022-10-21 03:17 UTC, laoboxie commented
> 加一下单元测试。

好的，我找个时间加一下

2022-10-21 07:59 UTC, coolyuantao requested changes

2022-10-21 07:59 UTC, coolyuantao commented on app/port/controller/AbstractController.ts
> +        if (allowSync && this.redirectNotFound) {
按当前的实现：在`exist | all`模式下，如果`syncNotFound: false`且`redirectNotFound: true`时，重定向功能将会是失效的。`redirectNotFound` 这个配置依赖于`syncNotFound`为`true`才能生效，这个不合理吧

2022-11-28 13:15 UTC, hezhengxu2018 commented
`syncNotFound`这个配置项应该也需要支持`none`的状态，即不主动同步`packages`直到该依赖被请求。根据目前的逻辑只要去获取依赖即会更新该依赖的所有版本，缓存依赖的方式不够“懒”。

2022-12-04 09:44 UTC, laoboxie commented on app/port/controller/AbstractController.ts
> +        if (allowSync && this.redirectNotFound) {
已修改。getAllowSync 方法移除 syncNotFound 的相关逻辑。

2022-12-04 09:46 UTC, laoboxie commented
> 加一下单元测试。

单测用例已添加。

2022-12-04 09:54 UTC, laoboxie commented
> `syncNotFound`这个配置项应该也需要支持`none`的状态，即不主动同步`packages`直到该依赖被请求。根据目前的逻辑只要去获取依赖即会更新该依赖的所有版本，缓存依赖的方式不够“懒”。

- none: don't sync npm package, just redirect it to sourceRegistry
node是不同步，直接重定向的上游源的

2022-12-05 01:54 UTC, hezhengxu2018 commented
> 

或者将配置项名称改成`syncOrCacheNotFound`如何？配置成`syncMode`为`none`时不会创建同步任务，仅缓存缺失的依赖，与描述并不相悖。
npm私库仅缓存的需求很常见，可以减少大量的存储空间，大部分npm私库都实现了这个功能。如果要为这个功能点再单独添加一个配置项会不会让人困惑增加理解成本？

2022-12-05 11:09 UTC, hezhengxu2018 commented
> > > 
> > 
> > 
> > 或者将配置项名称改成`syncOrCacheNotFound`如何？配置成`syncMode`为`none`时不会创建同步任务，仅缓存缺失的依赖，与描述并不相悖。 npm私库仅缓存的需求很常见，可以减少大量的存储空间，大部分npm私库都实现了这个功能。如果要为这个功能点再单独添加一个配置项会不会让人困惑增加理解成本？
> 
> 从你的描述来看，你指的仅缓存是不是 exist 模式，这个模式下不存在时是会进行同步的。

在`syncMode`为`exist`时还是会创建同步依赖的`schedule`去同步仓库内已有依赖的所有版本，如果是仅缓存使用的依赖那么`syncMode`必须是`none`。
举例来说，在启用了`syncNotFound`，同时`syncMode`为`exist`的配置下的新仓库：当通过此仓库去安装`lodash`的最新版本，在获取最新版本的`lodash`时会创建`schedule`去同步`lodash`的上百个版本。但是其余的这些版本我并不需要，对于一些包体积比较大的依赖或者发布的版本特别多的依赖则会尤其明显的增加存储与带宽的占用。
我的`仅缓存`的意思是不会创建同步的`schedule`（即`syncMode`为`none`），仅存储用户使用到的版本，不会同步该依赖的最新版本或该依赖的所有版本。

2023-01-11 05:47 UTC, fengmk2 commented
春节之前 review 完会合并发布。

2023-01-18 01:48 UTC, fengmk2 approved these changes

2023-01-18 01:52 UTC, fengmk2 commented on config/config.default.ts
> +    syncNotFound: false,
syncNotFound 默认值我改成 false 了，这个需要按需开启，因为一定用在互联网公开场景，会导致大流量瞬间将任务队列打满。

2023-01-18 01:58 UTC, merged

2023-01-18 01:58 UTC, fengmk2 commented
@laoboxie @coolyuantao 非常感谢两位的贡献💐！